In [12]:
import numpy as np
import pandas as pd

In [13]:
df = pd.read_csv('../titanic.csv')

In [17]:
df

Survived  Pclass     Sex   Age  Siblings/Spouses  Parents/Children  \
0           0       3    male  22.0                 1                 0   
1           1       1  female  38.0                 1                 0   
2           1       3  female  26.0                 0                 0   
3           1       1  female  35.0                 1                 0   
4           0       3    male  35.0                 0                 0   
..        ...     ...     ...   ...               ...               ...   
882         0       2    male  27.0                 0                 0   
883         1       1  female  19.0                 0                 0   
884         0       3  female   7.0                 1                 2   
885         1       1    male  26.0                 0                 0   
886         0       3    male  32.0                 0                 0   

        Fare   male  
0     7.2500   True  
1    71.2833  False  
2     7.9250  False  
3    53.1000  False  
4     8.0500   True  
..       ...    ...  
882  13.0000   True  
883  30.0000  False  
884  23.4500  False  
885  30.0000   True  
886   7.7500   True  

[887 rows x 8 columns]

In [18]:
df['male'] = df['Sex'] == 'male'

In [19]:
df

Survived  Pclass     Sex   Age  Siblings/Spouses  Parents/Children  \
0           0       3    male  22.0                 1                 0   
1           1       1  female  38.0                 1                 0   
2           1       3  female  26.0                 0                 0   
3           1       1  female  35.0                 1                 0   
4           0       3    male  35.0                 0                 0   
..        ...     ...     ...   ...               ...               ...   
882         0       2    male  27.0                 0                 0   
883         1       1  female  19.0                 0                 0   
884         0       3  female   7.0                 1                 2   
885         1       1    male  26.0                 0                 0   
886         0       3    male  32.0                 0                 0   

        Fare   male  
0     7.2500   True  
1    71.2833  False  
2     7.9250  False  
3    53.1000  False  
4     8.0500   True  
..       ...    ...  
882  13.0000   True  
883  30.0000  False  
884  23.4500  False  
885  30.0000   True  
886   7.7500   True  

[887 rows x 8 columns]

In [20]:
x = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values

In [22]:
y = df['Survived'].values

## Build a Logistic Regression Model with Sklearn

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
model = LogisticRegression()

In [25]:
x = df[['Fare', 'Age']].values

In [26]:
y = df['Survived'].values

In [27]:
model.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
model.coef_

array([[ 0.01615949, -0.01549065]])

In [29]:
model.intercept_

array([-0.51037152])

In [31]:
model.predict(x[:5])

array([0, 1, 0, 0, 0])

In [32]:
y_pred = model.predict(x)

In [35]:
(y== y_pred).sum()

580

In [36]:
(y== y_pred).sum() / y.shape[0]

0.6538895152198422

In [38]:
model.score(x,y)

0.6538895152198422